steps:
    # Install dependencies
    - name: 'gcr.io/cloud-builders/npm'
      entrypoint: 'npm'
      args: ['install']

    # Build the application
    - name: 'gcr.io/cloud-builders/npm'
      entrypoint: 'npm'
      args: ['run', 'build']

    # Deploy to target environment
    - name: 'gcr.io/cloud-builders/gsutil'
      entrypoint: 'gsutil'
      args:
          - '-m'
          - 'rsync'
          - '-r'
          - 'build'
          - 'gs://rasjobs/' # Make sure to replace 'rasjobs' with your actual bucket name
